#!/usr/bin/env sh

workspace="$1"
supported_schemes_systems="base16 base24"

if [ -z $workspace ]; then
  echo "Missing 'workspace' argument"
fi

for scheme_system in $supported_schemes_systems; do
  for scheme_path in "$workspace/$scheme_system"/*; do
    scheme_filename=$(basename -- "$scheme_path")

    case "$scheme_filename" in
      *.yaml)
        if ! $(grep -q "author" "$scheme_path" \
          && grep -q "name" "$scheme_path" \
          && grep -q "palette" "$scheme_path" \
          && grep -q "system" "$scheme_path" \
          && grep -q "variant" "$scheme_path"); then

          echo "Error: Missing one of the required yaml properties (author|name|palette|system|variant) in $scheme_path"
          exit 1
        fi
      ;;
    esac
  done
done
